language: php
sudo: required
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
        - $HOME/.php-cs-fixer

env:
    global:
        - TEST_COMMAND="composer test"
        - COMPOSER_FLAGS="--prefer-dist"
        - SYMFONY_PHPUNIT_VERSION=6.5

jobs:
  include:
    - name: "Code style"
      php: 7.2
      services:
        - docker
      before_install:
        - mkdir -p "$HOME/.php-cs-fixer"
        - composer require friendsofphp/php-cs-fixer
      script:
        - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
        - docker run --rm -v "$PWD":/app phpstan/phpstan analyse

    - name: "PHP nightly - HTTP/2 Server Push"
      php: 7.2
      services:
        - docker
      before_install:
        - docker network create buzz-net
        - docker build -t buzz/tests .
        - docker run -d --name test-server -p 127.0.0.1:8022:80 buzz/tests
        - docker network connect buzz-net test-server
        - docker ps -a
      before_script:
        - ./vendor/bin/http_test_server > /dev/null 2>&1 &
      script:
        - docker run -it --rm --network buzz-net -v "$PWD":/usr/src/myapp -w /usr/src/myapp tommymuehle/docker-alpine-php-nightly php vendor/bin/phpunit

    - name: "Integration tests"
      php: 7.2
      services:
        - docker
      before_install:
        - docker build -t buzz/tests .
        - docker run -d -p 127.0.0.1:8022:80 buzz/tests
        - docker ps -a
      before_script:
        - ./vendor/bin/http_test_server > /dev/null 2>&1 &
      script:
        - composer test-ci
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/coverage.xml

      # Test with lowest dependencies
    - name: "Low dependencies"
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

      # Test the latest stable release
    - php: 7.1
    - php: 7.2
    - php: 7.3

      # Force some major versions of Symfony
    - name: "Symfony 3.x"
      php: 7.2
      env: DEPENDENCIES="dunglas/symfony-lock:^3"
    - name: "Symfony 4.x"
      php: 7.2
      env: DEPENDENCIES="dunglas/symfony-lock:^4"

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND
